---
title: "Walkthrough"
author: "Joseph Stachelek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Walkthrough

## Load package

```{r eval=FALSE}
library(spectraling)
```

## Read data

```{r ,eval=FALSE}
dataTerr     <- read.csv("../data-raw/terrData.csv", header = T)
dataFW       <- read.csv("../data-raw/freshData.csv", header = T)
i <- which(colnames(dataFW) == "hu12_states")
dataTerrFW   <- merge(dataTerr, dataFW[-i], by.x = "zoneid", by.y = "zoneid")
islands      <- read.csv("../data-raw/islandIdx.csv", header = T)
latLong18876 <- read.csv("../data-raw/latLong18876.csv", header = T)
NB18876      <- read.csv("../data-raw/NB_18876.csv", header = T)
```

## Prep Input

```{r prep input, eval=FALSE}
# generate the input when we restrict the
# data to dataTerrFW's of state Missouri, 
# and no islands inculded.
input <- generateData(type = dataTerrFW, islands = islands, 
                      latLong = latLong18876, NB18876, islandsIn = F, 
                      states = c("MO"), conFactor = 1)
```

```{r ,eval=FALSE}
results <- speCluster(data = input$data, conMatrix = input$conMatrix, 
                      cluster.number = 10)
summary(results)
results$SS
head(results$clusters)
mapping(lat = input$latLong[,1], long = input$latLong[,2],
         clusters = results$clusters)

```
